Cleaning Tabel Stores

In [ ]:
import numpy as np
import pandas as pd

In [68]:
df = pd.read_csv('/content/Stores.csv')

In [69]:
df.head()

   StoreKey    Country                         State  Square Meters  Open Date
0         1  Australia  Australian Capital Territory          595.0   1/1/2008
1         2  Australia            Northern Territory          665.0  1/12/2008
2         3  Australia               South Australia         2000.0   1/7/2012
3         4  Australia                      Tasmania         2000.0   1/1/2010
4         5  Australia                      Victoria         2000.0  12/9/2015

In [70]:
df.dtypes

StoreKey           int64
Country           object
State             object
Square Meters    float64
Open Date         object
dtype: object

In [71]:
# Mengubah format data
df['Country'] = df['Country'].astype('category')
df['State'] = df['State'].astype('category')

df['Open Date'] = pd.to_datetime(df['Open Date'])
df['Square Meters'] = df['Square Meters'].astype('Int64')

In [72]:
# cek nilai kosong
df.isna().sum()

StoreKey         0
Country          0
State            0
Square Meters    1
Open Date        0
dtype: int64

In [73]:
# melihat data yang null
df[df['Square Meters'].isna()]

    StoreKey Country   State  Square Meters  Open Date
66         0  Online  Online           <NA> 2010-01-01

In [74]:
# mengisi nilai null
df['Square Meters'] = df['Square Meters'].fillna(0)

In [75]:
# menghitung nilai unik pada setiap kolom
for col in df.columns:
  print(f'{col}: {df[col].nunique()}')

StoreKey: 67
Country: 9
State: 67
Square Meters: 37
Open Date: 25

In [76]:
df.describe()

        StoreKey  Square Meters                      Open Date
count  67.000000           67.0                             67
mean   33.000000    1381.268657  2011-06-24 00:42:59.104477696
min     0.000000            0.0            2005-03-04 00:00:00
25%    16.500000         1095.0            2009-06-03 00:00:00
50%    33.000000         1330.0            2010-06-03 00:00:00
75%    49.500000         2000.0            2013-06-07 00:00:00
max    66.000000         2105.0            2019-03-05 00:00:00
std    19.485037     597.120834                            NaN

In [77]:
# mengganti nama kolom
df.columns = df.columns.str.replace(' ','_').str.lower()

In [78]:
# mengubah storekey menjadi store_key
df.rename(columns={'storekey':'store_key'}, inplace=True)

In [79]:
df

,store_key,country,state,square_meters,open_date
0,1,Australia,Australian Capital Territory,595,2008-01-01
1,2,Australia,Northern Territory,665,2008-01-12
2,3,Australia,South Australia,2000,2012-01-07
3,4,Australia,Tasmania,2000,2010-01-01
4,5,Australia,Victoria,2000,2015-12-09
...,...,...,...,...,...
62,63,United States,Utah,2000,2008-03-06
63,64,United States,Washington DC,1330,2010-01-01
64,65,United States,West Virginia,1785,2012-01-01
65,66,United States,Wyoming,840,2014-01-01
66,0,Online,Online,0,2010-01-01

In [81]:
df.to_csv('stores_cleaned.csv')

Cleaning Tabel Sales

In [61]:
df_sales = pd.read_csv('/content/Sales.csv')

In [62]:
df_sales.head()

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD

In [113]:
# mengubah format text untuk semua kolom
df_sales.columns = df_sales.columns.str.replace(' ','_').str.lower()
df_sales.rename(columns= {'customerkey': 'customer_key',
                          'storekey': 'store_key',
                          'productkey': 'product_key'},
                 inplace=True)
df_sales.columns

Index(['order_number', 'line_item', 'order_date', 'delivery_date',
       'customer_key', 'store_key', 'product_key', 'quantity',
       'currency_code'],
      dtype='object')

In [114]:
df_sales.dtypes

order_number      int64
line_item         int64
order_date       object
delivery_date    object
customer_key      int64
store_key         int64
product_key       int64
quantity          int64
currency_code    object
dtype: object

In [115]:
# mengubah tipe data pada setiap kolom
df_sales['order_date'] = pd.to_datetime(df_sales['order_date'])
df_sales['delivery_date'] = pd.to_datetime(df_sales['delivery_date'])
df_sales['currency_code'] = df_sales['currency_code'].astype('category')

In [117]:
# cek nilai yang nan atau kosong
df_sales.isnull().sum()

order_number         0
line_item            0
order_date           0
delivery_date    49719
customer_key         0
store_key            0
product_key          0
quantity             0
currency_code        0
dtype: int64

In [120]:
cek_sales_null = df_sales.loc[df_sales['delivery_date'].isna()]
cek_sales_null

,order_number,line_item,order_date,delivery_date,customer_key,store_key,product_key,quantity,currency_code
0,366000,1,2016-01-01,NaT,265598,10,1304,1,CAD
6,366004,1,2016-01-01,NaT,1107461,38,163,6,GBP
7,366004,2,2016-01-01,NaT,1107461,38,1529,2,GBP
8,366005,1,2016-01-01,NaT,844003,33,421,4,EUR
9,366007,1,2016-01-01,NaT,2035771,43,1617,1,USD
...,...,...,...,...,...,...,...,...,...
62867,2243025,1,2021-02-20,NaT,1909290,49,1128,2,USD
62868,2243025,2,2021-02-20,NaT,1909290,49,2511,2,USD
62869,2243026,1,2021-02-20,NaT,1737466,49,58,6,USD
62872,2243028,1,2021-02-20,NaT,1728060,66,1584,3,USD
62879,2243030,1,2021-02-20,NaT,1216913,43,632,3,USD

In [ ]:
# untuk saat ini tidak dilakukan penanganan missing value pada kolom delivery_date

In [126]:
df_sales.duplicated().sum()

np.int64(0)

In [121]:
df_sales.to_csv('sales_cleaned.csv')

Cleaning Tabel Customers

In [86]:
df_customers = pd.read_csv('/content/Customers.csv', encoding='latin1')

In [87]:
df_customers.head()

,CustomerKey,Gender,Name,City,State Code,State,Zip Code,Country,Continent,Birthday
0,301,Female,Lilly Harding,WANDEARAH EAST,SA,South Australia,5523,Australia,Australia,7/3/1939
1,325,Female,Madison Hull,MOUNT BUDD,WA,Western Australia,6522,Australia,Australia,9/27/1979
2,554,Female,Claire Ferres,WINJALLOK,VIC,Victoria,3380,Australia,Australia,5/26/1947
3,786,Male,Jai Poltpalingada,MIDDLE RIVER,SA,South Australia,5223,Australia,Australia,9/17/1957
4,1042,Male,Aidan Pankhurst,TAWONGA SOUTH,VIC,Victoria,3698,Australia,Australia,11/19/1965

In [88]:
df_customers.dtypes

CustomerKey     int64
Gender         object
Name           object
City           object
State Code     object
State          object
Zip Code       object
Country        object
Continent      object
Birthday       object
dtype: object

In [91]:
# mengubah nama kolom
df_customers.columns = df_customers.columns.str.replace(' ','_').str.lower()

df_customers.rename(columns={'customerkey':'customer_key'}, inplace=True)

# cek kolom
df_customers.columns

Index(['customer_key', 'gender', 'name', 'city', 'state_code', 'state',
       'zip_code', 'country', 'continent', 'birthday'],
      dtype='object')

In [93]:
# mengubah tipe data tiap-tiap kolom
col_category = ['gender', 'city', 'state_code', 'state', 'zip_code', 'country', 'continent']

for col in col_category:
  df_customers[col] = df_customers[col].astype('category')

df_customers['birthday'] = pd.to_datetime(df_customers['birthday'])

In [95]:
# periksa sampel random
df_customers.sample(5)

,customer_key,gender,name,city,state_code,state,zip_code,country,continent,birthday
6185,856365,Male,Cornelis Dogan,Nijverdal,OV,Overijssel,7441 HD,Netherlands,Europe,1980-06-05
8171,1156927,Female,Sienna Bartlett,FIVE ASH DOWN,Wealden,Wealden,TN22 9GS,United Kingdom,Europe,1935-10-11
11651,1621372,Female,Stephanie Wood,Conchas Dam,NM,New Mexico,88416,United States,North America,1961-06-25
4760,644237,Male,Arber Simard,CHELLES,IL,Île-de-France,77500,France,Europe,1969-08-22
10440,1463092,Female,Lara Wilson,Dothan,AL,Alabama,36303,United States,North America,1975-06-14

In [96]:
# cek data duplikat
df_customers.duplicated().sum()

np.int64(0)

In [97]:
df_customers.isnull().sum()

customer_key     0
gender           0
name             0
city             0
state_code      10
state            0
zip_code         0
country          0
continent        0
birthday         0
dtype: int64

In [100]:
mask = df_customers['state_code'].isna()
df_customers.loc[mask]

,customer_key,gender,name,city,state_code,state,zip_code,country,continent,birthday
5304,729681,Female,Rossana Padovesi,Polvica,NaN,Napoli,80035,Italy,Europe,1981-04-18
5316,732289,Male,Indro Piccio,Varcaturo,NaN,Napoli,80014,Italy,Europe,1949-02-24
5372,742042,Male,Amaranto Loggia,Casaferro,NaN,Napoli,80034,Italy,Europe,1936-03-14
5377,742886,Female,Edmonda Capon,Terzigno,NaN,Napoli,80040,Italy,Europe,1963-08-06
5378,743343,Female,Ambra Sagese,Pomigliano D'Arco,NaN,Napoli,80038,Italy,Europe,1961-01-05
5485,759705,Male,Callisto Lo Duca,Casilli,NaN,Napoli,80047,Italy,Europe,1976-08-28
5525,765589,Male,Michelino Lucchesi,Pompei Scavi,NaN,Napoli,80045,Italy,Europe,1947-11-13
5531,766410,Male,Adelmio Beneventi,Licola,NaN,Napoli,80078,Italy,Europe,1940-01-13
5631,781667,Female,Ilda Manna,Napoli,NaN,Napoli,80134,Italy,Europe,1977-05-08
5695,789177,Male,Calogero Folliero,Mariglianella,NaN,Napoli,80030,Italy,Europe,2000-03-03

In [103]:
# mengisi state code untuk NAPOLY yaitu NA
# menambahkan 'NA' sebagai kategori terlebih dahulu
df_customers['state_code'] = df_customers['state_code'].cat.add_categories('NA')
df_customers.loc[mask, 'state_code'] = 'NA'

In [111]:
df_customers.nunique()

customer_key    15266
gender              2
name            15118
city             8258
state_code        468
state             512
zip_code         9505
country             8
continent           3
birthday        11270
dtype: int64

In [112]:
df_customers.to_csv('customers_cleaned.csv')

Cleaning Tabel Products

In [170]:
df_products = pd.read_csv('/content/Products.csv')

In [182]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_key      2517 non-null   int64
 1   product_name     2517 non-null   object
 2   brand            2517 non-null   category
 3   color            2517 non-null   category
 4   unit_cost_usd    2517 non-null   float64
 5   unit_price_usd   2517 non-null   float64
 6   subcategory_key  2517 non-null   int64
 7   subcategory      2517 non-null   category
 8   category_key     2517 non-null   int64
 9   category         2517 non-null   category
 10  margin           2517 non-null   float64
dtypes: category(4), float64(3), int64(3), object(1)
memory usage: 150.3+ KB

In [172]:
# mengubah nama kolom
df_products.columns = df_products.columns.str.replace(' ','_').str.lower()
df_products.rename(columns={'productkey':'product_key',
                            'subcategorykey':'subcategory_key',
                            'categorykey':'category_key'},
                   inplace=True)

In [173]:
df_products.head()

,product_key,product_name,brand,color,unit_cost_usd,unit_price_usd,subcategory_key,subcategory,category_key,category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio

In [181]:
# mengubah tipe data category
cols_cat = ['brand', 'color', 'subcategory', 'category']

df_products[cols_cat] = df_products[cols_cat].astype('category')

In [174]:
# mengubah format unit cost dan unit price
df_products['unit_cost_usd'] = (df_products['unit_cost_usd']
                                .astype(str)
                                .str.replace(r'[^0-9.]', '', regex=True)
                                .astype(float))
df_products['unit_price_usd'] = (df_products['unit_price_usd']
                                .astype(str)
                                .str.replace(r'[^0-9.]', '', regex=True)
                                .astype(float))

In [175]:
# memeriksa apakah semua nilai valid
df_products.loc[
    (df_products['unit_cost_usd'] <= 0) |
    (df_products['unit_price_usd'] <= 0)
]

Empty DataFrame
Columns: [product_key, product_name, brand, color, unit_cost_usd, unit_price_usd, subcategory_key, subcategory, category_key, category]
Index: []

In [176]:
# membuat kolom baru
df_products['margin'] = df_products['unit_price_usd'] - df_products['unit_cost_usd']

In [177]:
# memeriksa apakah margin selalu positif
df_products.loc[
    (df_products['margin'] <= 0) |
    (df_products['margin'] <= 0)
]

Empty DataFrame
Columns: [product_key, product_name, brand, color, unit_cost_usd, unit_price_usd, subcategory_key, subcategory, category_key, category, margin]
Index: []

In [178]:
df_products.isnull().sum()

product_key        0
product_name       0
brand              0
color              0
unit_cost_usd      0
unit_price_usd     0
subcategory_key    0
subcategory        0
category_key       0
category           0
margin             0
dtype: int64

In [183]:
df_products.duplicated().sum()

np.int64(0)

In [184]:
df_products.to_csv('products_cleaned.csv')

Cleaning Tabel Exchange Rates

In [124]:
df_er = pd.read_csv('/content/Exchange_Rates.csv')

In [185]:
df_er.head()

       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415

In [188]:
# memperbaiki nama kolom
df_er.columns = df_er.columns.str.lower()

In [192]:
df_er.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11215 entries, 0 to 11214
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      11215 non-null  datetime64[ns]
 1   currency  11215 non-null  category
 2   exchange  11215 non-null  float64
dtypes: category(1), datetime64[ns](1), float64(1)
memory usage: 186.5 KB

In [191]:
# mengubah tipe data
df_er['currency'] = df_er['currency'].astype('category')
df_er['date'] = pd.to_datetime(df_er['date'])

In [193]:
df_er.to_csv('exchange_rates_cleaned.csv')